name: Lint code and run tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [ 12.x, 13.x, 14.x ]
        redis-version: [ 5.0, 6.0 ]
    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run test
        env:
          REDIS_URL: "redis://localhost"
